### ISSUE TITLE
TypeError: Only absolute URLs are supported 

### ISSUE THREAD

**Issue by sebpowell** [Xunnamius/next-test-api-route-handler#303] opened 2021-08-22 08:09 UTC
<details open><summary><strong>Problematic behavior</strong></summary>
I've tried setting this up as explained in the docs. When I try running the test suite, my test fails with the message  `TypeError: Only absolute URLs are supported`
</details>

<details><summary><strong>Reproduction steps</strong></summary>
Here's what my code looks like:

<img width="872" alt="Screenshot 2021-08-22 at 09 01 19" src="https://user-images.githubusercontent.com/1786366/130347236-2d1d0bdd-fd26-45e4-beb6-f256bbc16d72.png">

I tried setting an absolute URL (e.g. http://localhost:3000/pages/api/me), but that didn't work. I also tried removing 'pages' (e.g. /api/me), and no luck there either. 

I'm using the Next.js runtime, so my `/api` directory is inside `/pages`. So I tried switching to a Node.js runtime by moving the `/api` directory to the root folder, but no luck there either. 

I may have missed something in the docs, but can't see it – this looks like a great, and much needed package, so would love to get this working!
</details>

<details><summary><strong>Expected behavior</strong></summary>
I would expect to be able to run the test suite. 
</details>

**Comment by Xunnamius** [comment] 2021-08-22 23:09
Hi Sebastien!

`request.url` is a dummy value fed to the handler you're testing (defaults to `"/"`). It should only be set if your handler or middleware expects it to be something specific (like in the Apollo example).

In most cases, you can leave `url` at its default. This is because, after parsing the query string (if it exists), `request.url` is totally ignored by NTARH—even when routing `fetch()` calls to the dummy server—and it has no relation to how your project is laid out on disk. This is part of what makes it possible to run these unit tests in isolation 🙂. Moreover, with Next.js routing being filesystem-based, it's not usually necessary or desirable to set `request.url` manually (see the [quick start](https://github.com/Xunnamius/next-test-api-route-handler#usage) and [unreliable api](https://github.com/Xunnamius/next-test-api-route-handler#testing-an-unreliable-api-handler--pagesapiunreliable) examples); it's more important to import the right handler from the right path, which it seems like you've done.

Can you create a minimal example repository that reproduces your failing test suite and share the link?

**Comment by Xunnamius** [comment] 2021-08-29 01:41
Closing this for now since this seems like a non-NTARH issue, but feel free to comment with more info :)

**Closed by Xunnamius** 2021-08-29 01:41 UTC
Labels: bug
